/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package contactservice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ContactTest {
    // test case for creating a contact
    @Test
    public void testContact() {
        Contact contact = new Contact("1234567890", "Tagoe", "Nii Amatey", "1234567890", "75154 RX st");
        assertEquals("1234567890", contact.getContactID());
        assertEquals("Nii Amatey", contact.getFirstName());
        assertEquals("Tagoe", contact.getLastName());
        assertEquals("1234567890", contact.getPhoneNumber());
        assertEquals("75154 RX st", contact.getAddress());
    }
    // test case for validating a contact
    @Test
    public void testContactInvalidID() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact(null, "Nii Amatey", "Tagoe", "1234567890", "123 Main St");
        });
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("12345678901", "Nii Amatey", "Tagoe", "1234567890", "123 Main St");
        });
    }
    //test case for validating a contact last name
    @Test
    public void testContactValidateLastName() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", null, "Nii Amatey", "1234567890", "75154 RX Street");
        });
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "LastNameIsTooLong", "Nii Amatey", "1234567890", "75154 RX Street");
        });
    }
    //test case for validating a contact first name
    @Test
    public void testContactValidateFirstName() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", null, "1234567890", "75154 RX Street");
        });
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", "FirstNameIsTooLong", "1234567890", "75154 RX Street");
        });
    }
    //test case for validating a contact phone number
    @Test
    public void testContactValidatePhoneNumber() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", "Nii Amatey", null, "75154 RX Street");
        });
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", "Nii Amatey", "IncorrectPhoneNumber", "75154 RX Street");
        });
    }
    //test case for validating a contact address
    @Test
    public void testContactValidateAddress() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", "Nii Amatey", "1234567890", null);
        });
        assertThrows(IllegalArgumentException.class, () -> {
            new Contact("1234567890", "Tagoe", "Nii Amatey", "1234567890", "ThisAddressIsTooLongThisAddressIsTooLong");
        });
    }
}